package com.kiero.global.notification.domain;

public enum PushNotificationType {
	// 부모 이벤트
	PARENT_DAILY_START,
	SCHEDULE_VERIFIED,
	FIRE_LIT,
	MISSION_COMPLETE,
	COUPON_PURCHASED,
	SCHEDULE_SKIPPED,
	PARENT_SCHEDULE_REMINDER,

	// 자녀 이벤트
	CHILD_DAILY_START,
	CHILD_NEXT_JOURNEY,
	CHILD_MISSION_INCOMPLETE,
	SCHEDULE_CREATED,
	SCHEDULE_DELETED,
	SCHEDULE_MODIFIED,
}